spring:
  application:
    name: ConsumerService
  cloud:
    loadbalancer:
      retry:
        enabled: true   #enable retry

server:
  port: 9094

eureka:
  instance:
    instance-id: consumerService:${spring.application.instance-id:${random.value}}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 5   #每隔多久向eureka續約服務
    lease-expiration-duration-in-seconds: 10   #多久後沒續約就過期
  client:
    register-with-eureka: true   #向註冊中心註冊自己
    fetch-registry: true   #需要檢索服務
    service-url:
      defaultZone: http://peer1:9090/eureka,http://peer2:9091/eureka

ribbon:
  MaxAutoRetries: 1  #單台server最多retry次數
  MaxAutoRetriesNextServer: 2  #切換server最多次數
  OkToRetryOnAllOperations: true
  ServerListRefreshInterval: 2000   # Interval to refresh the server list from the source
  ReadTimeout: 2000
  ConnectTimeout: 2000

niws:
    loadbalancer:
        availabilityFilteringRule:
            activeConnectionsLimit: 10   #for availabilityFilteringRule最大server併發數

#有空嘗試Spring cloud 3.5 Ignore Network Interfaces的內容

management:
  security:
    enabled: false   #因為還沒加入spring Security, 否則出現 s.b.a.e.m.MvcEndpointSecurityInterceptor : Full authentication is required to access actuator endpoints. Consider adding Spring Security or set 'management.security.enabled' to false.