spring:
  application:
    name: ConsumerService

server:
  port: 9094

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5   #每隔多久向eureka續約服務
    lease-expiration-duration-in-seconds: 10   #多久後沒續約就過期
    instance-id: consumerService:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true   #向註冊中心註冊自己
    fetch-registry: true   #需要檢索服務
    service-url:
      defaultZone: http://peer1:9090/eureka,http://peer2:9091/eureka

management:
  security:
    enabled: false   #因為還沒加入spring Security, 否則出現 s.b.a.e.m.MvcEndpointSecurityInterceptor : Full authentication is required to access actuator endpoints. Consider adding Spring Security or set 'management.security.enabled' to false.